import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v14-appRouter";
import { Noto_Sans_JP } from "next/font/google";
import Header from "./Header";
import { CookiesProvider } from "next-client-cookies/server";

// 1. フォントの読み込み
const NotoSansJP = Noto_Sans_JP({
  weight: ["400", "700"],
  subsets: ["latin"],
  preload: true,
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={NotoSansJP.className}>
        <AppRouterCacheProvider>
          <Header></Header>
          <CookiesProvider>{children}</CookiesProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
